### PR TITLE
Update dependancy

### PR DESCRIPTION
**Pull request by estella144**
This is 12 commits behind. Merging those will give us those new changes.

### CODE REVIEW

**Comment by RobFog** [comment]
We aren't using Trac currently. Please slow down and put more thought into your comments, pull requests and bug reports. This is getting annoying.

**Comment by RobFog** [comment]
Please stop posting unnecessary "me too" comments as you just did at https://github.com/adium/adium/issues/20

**Comment by estella144** [comment]
@RobFog that is not happening any more. Besides, how are people supposed to know we are not using a specific thing?

**Comment by RobFog** [comment]
Good.

I would suggest
* making changes for things that are known to be used or
* checking with other members of the project whether a change is useful.

**Comment by estella144** [comment]
@RobFog "known to be used". What do you mean by that?

**Comment by RobFog** [comment]
If you know.

**Comment by estella144** [comment]
@RobFog I don't know!

**Comment by RobFog** [comment]
I assumed as much. Hence my suggestion to check with others before creating a pull request for something of which you don't know whether it is in use.

**Comment by RobFog** [comment]
https://github.com/adium/adium/issues/20#issuecomment-796908493 – again, no "me too" comments, please. If you want to indicate agreement, you can use the "thumbs up" reaction.

**Comment by estella144** [comment]
@RobFog you are just referring to the same thing. I'm learning and frankly, I've grown out of that now!

**Pull request closed without merging**
